### ISSUE TITLE
Any tips to install Verdi on OS X? 

### ISSUE THREAD

**Issue by c4milo** [uwplse/verdi#11]

**Comment by wilcoxjay** [comment]
I'm not an OS X user, so this is untested advice :)

Grab the DMG for Coq 8.5beta2 from https://coq.inria.fr/coq-85 and install.

Open Terminal and type `coqc --version`. You should see something like

        The Coq Proof Assistant, version 8.5beta2

At this point, Coq has been successfully installed. 

After cloning Verdi, you can type `make` in the top level directory to fire off a rather long build process. Depending on what exactly you're interested in, you may or may not need to build everything. If you don't care about checking all the proofs, you can kill the build after you start seeing files that end in Proof.v :) 

To run vard, the verified key-value store similar in spirit to etcd, you'll need to make sure OCaml is installed and then follow the instructions in the README under "The vard Key-Value Store".

Thanks for your interest and feel free to ask any further questions!

**Comment by c4milo** [comment]
@wilcoxjay these instructions should be enough! thank you!

I would like to play with Verdi and see if I can test Consul's K/V store as well as Consul's Raft implementation. Too dreamy?

**Comment by wilcoxjay** [comment]
Verdi is a framework for implementing distributed systems in Coq and then proving things about those systems. The goal is to produce highly reliable systems with mathematically proven guarantees about the behavior of these systems. Verdi's proofs are done manually and then checked with Coq's proof checker. Verdi does not analyze existing code or systems.
