### ISSUE TITLE
Modelling multithreaded applications

### ISSUE THREAD

**Issue by k32** [uwplse/verdi#122]
After reading the papers and skimming through the examples I noticed that verdi doesn't seem to be suited for modelling concurrent applications, as handler callbacks are deterministic (prove me wrong).

Perhaps something like actor-based concurrency can be emulated using custom network semantics with extended names, say `(node * thread)` and different message delivery guarantees depending on `node` part. Even something like shared state can be emulated by an actor... Yet this solution seems too finicky and I would avoid taking this path unless I absolutely have to.

Question: was I right about handlers being deterministic? If so, what is the best approach to the problem in your opinion?

**Comment by hackedy** [comment]
Hi, thanks for your question! Yes, handlers in Verdi are total functions, so they are deterministic. Most expressive limitations of Verdi can be addressed by adding new network semantics. However it's not obvious to me what exactly this would look like for concurrency. I would expect the semantics to be super finicky, as you said, and then you would want to build a sound program logic on top of the semantics to make it possible for a mere mortal to prove things. But I have no experience proving properties of concurrent programs, so I can only speculate. Sorry!

In the future, please use verdi@cs.washington.edu for design questions. We try to reserve Github issues for bugs.

**Comment by palmskog** [comment]
Conventional Verdi systems are essentially coarse-grained actor systems where actors are either fixed at initialization time or started up nondeterministically during execution. The OCaml runtime gives operating system process level concurrency in practice. As far as I know, there is no proof assistant framework that supports the full range of actor behavior (e.g., actors spawning actors and delegating behavior to other actors) and allows obtaining executable code.

If all that's needed is node-level fine-grained concurrency (without any actor-based encapsulation or reasoning) that should be easy to accomplish with (1) FCSL and [Disel](https://github.com/DistributedComponents/disel) or (2) Iris and [Aneris](https://iris-project.org/pdfs/2019-aneris-submission.pdf).

Handler nondeterminism is in my mind a completely orthogonal question. It would be possible to make a Verdi network semantics that allowed nodes to behave probabilistically, using any of the tens of approaches to probability theory in Coq.
