### ISSUE TITLE
What commit works for verdi with coq 8.12?

### ISSUE THREAD

**Issue by brando90** [uwplse/verdi#138]
Sincere apology, perhaps this isn't supported but given all my efforts I thought it would be worth at least asking before giving up...is there a commit that would work with verdi and coq 8.12?

I did try `--ignore-constraints-on=coq ` but it doesn't seem to have given me the same success as it did with cheerios https://github.com/uwplse/cheerios/issues/20

this is what I tried:
```
git clone git@github.com:uwplse/verdi.git deps/verdi
(cd coq-projects/verdi && opam install -y --ignore-constraints-on=coq .)
# this doesn't seem to do anything different than the above attempt, above uses dev & ends up using verdi-runtime
#git clone git@github.com:uwplse/verdi.git deps/verdi
#(cd deps/verdi && git checkout fdb4ede19d2150c254f0ebcfbed4fb9547a734b0 && git rev-parse HEAD)
#(cd deps/verdi && git checkout 3d22ce073f7d16da58eb8e1aa3c71bf8f588a04f && git rev-parse HEAD)
#(cd deps/verdi && git checkout 35508f2af94f9da979ece0cbdfa191019f2c5478 && git rev-parse HEAD) # right before coq >=8.14 warning
#(cd deps/verdi && git checkout cb016cf9d2ae61ff757a0b6fa443b391a5416b63 && git rev-parse HEAD)  # coq >=8.14 warning
#(cd deps/verdi && opam install -y .)
```

**Comment by brando90** [comment]
needed due to this: https://github.com/UCSD-PL/proverbot9001/issues/92

**Comment by palmskog** [comment]
The only Coq versions we support are 8.14+. Please solve any issues in your own fork.
