### ISSUE TITLE
Server assumes that it can read the entire client request with a single recv call

### ISSUE THREAD

**Issue by pfons** [uwplse/verdi#41]
If the server is not able to read with one call the entire client request, which is sent over TCP, the server wrongly presumes that the client is disconnected and throws an exception (function _read_from_socket_ in file _Shim.ml_). 

The problem can be usually reproduced by simply sending the requests using two send calls on the client side.

**Comment by palmskog** [comment]
This issue was moved to uwplse/verdi-raft#53
