### ISSUE TITLE
Client-server marshaling allows users to inject commands and to crash the server

### ISSUE THREAD

**Issue by pfons** [uwplse/verdi#42]
The server-client communication protocol relies on spaces to delimit the arguments of requests and newlines to delimit the requests, which are sent over TCP connections. Because neither validation is made on the characters of the command arguments (keys and values) nor are the meta-characters escaped (newlines and spaces), by providing specially crafted input users of _vard.py_ are able to: 1) crash the server; 2) inject commands that are executed by the servers and cause subsequent requests to return wrong results.

To reproduce the bug it suffices to create a client application that issues the following _vard.py_ library calls:
1) Crash server:
`GET("key1 - - \n")`

During the execution of the _GET_ the leader crashes and before it terminates the leader produces the following error message:

```
client disconnected: received invalid input
Fatal error: exception Unix.Unix_error(Unix.EBADF, "send", "")
```

2) Inject commands:

```
PUT(key1,key1) = key1
PUT(key2,key2) = key2
PUT(key3,key3) = key3
GET(key1 - - \n132201621 216857 GET key2) = key1
GET(key1) = key2
GET(key2) = key1
GET(key3) = key2
```

Note that the last three _GET_ operations produce an incorrect result.

**Comment by palmskog** [comment]
This issue was moved to uwplse/verdi-raft#54
