### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by siddharthist** [uwplse/verdi#81]
Hi there, where can I find the documentation for this library?

**Comment by wilcoxjay** [comment]
Hi,

Thanks for your interest!

We have some sources of high-level documentation linked from the [website](http://verdi.uwplse.org/). I'd start by reading the blog posts, and then the PLDI '15 paper. If you want to know more about our verification of the Raft consensus protocol, then check out the CPP '16 paper as well.

We're also happy to answer specific questions you might have. You can file further issues here, send an email to `verdi@cs.washington.edu`, or chat with us in `#uwverdi` on freenode.

Unfortunately, the code itself is not particularly well documented. I'd be happy to add documentation to specific parts in response to your questions, or merge PRs that add documentation. (Perhaps that's wishful thinking on my part 😄 ...)

**Comment by siddharthist** [comment]
@wilcoxjay Thanks, I think I figured out what I needed from the blog post!
